#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     proto,          sensorI2CCustom9V)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     pod2Drive,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     pod3Drive,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     pod1Drive,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     pod0Drive,     tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    pod0Steer,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    pod1Steer,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    pod2Steer,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    pod3Steer,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define GYRO gyro

#include "JoystickDriver.c"
#include "LordSwerve.c"

/*
task changer()
{
  while ( true )
  {
    for ( int i = 0; i < 4; i++ )
    {
      setModuleTarget(i, 512);
    }
    wait1Msec(2000);
    for ( int i = 0; i < 4; i++ )
    {
      setModuleTarget(i, 1512);
    }
    wait1Msec(2000);
  }
}
*/
task main()
{
  bDisplayDiagnostics = false;
  initGyro();
  initSwerveDrive();
  //StartTask(changer);
  for ( int i = 0; i < 4; i++ )
  {
    setModuleTarget(i, 1024);
    setModuleSpeed(i, 0);
  }
  waitForStart();

  while ( true )
  {
    getJoystickSettings(joystick);

    //for ( int i = 0; i < 4; i++ )
    //{
    //  nxtDisplayString(i+1, "%i - %i - %i", i, modules[i].truePos, modules[i].Rollovers);
    //}
  /*  if ( abs(modules[3].turnPID.error) > 500 )
    {
      eraseDisplay();
      while( true )
      {
        servo[pod0Steer] = 127;
        servo[pod1Steer] = 127;
        servo[pod2Steer] = 127;
        servo[pod3Steer] = 127;

        eraseDisplay();
        nxtDisplayString(1, "Prev: %i", modules[3].lastPos);
        nxtDisplayString(2, "Cur: %i", modules[3].truePos);
      }
    }*/

   // if ( abs(joystick.joy1_x2) > 10 )
   //   chassisRotation();
   // else
   fieldCentricCrab();

   updateSwerveDrive();
  }

}
