#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     proto,          sensorI2CCustom9V)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     pod0Drive,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     pod3Drive,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     pod1Drive,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     pod2Drive,     tmotorNormal, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    pod0Steer,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    pod1Steer,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    pod2Steer,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    pod3Steer,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "LordSwervev2.c"
#include "JoystickDriver.c"
int rotateX(int x, int y, float theta)
{
  float cosA = cos(theta*(PI/180.0));
  float sinA = sin(theta*(PI/180.0));
  return (int)x*cosA-y*sinA;
}

int rotateY(int x, int y, float theta)
{
  float cosA = cos(theta*(PI/180.0));
  float sinA = sin(theta*(PI/180.0));
  return (int)x*sinA+y*cosA;
}

task main()
{
  //waitForStart();
  bDisplayDiagnostics = false;
  initSwerve();
  //massSet(1000);
  while ( true )
  {
    getJoystickSettings(joystick);
    int x = rotateX(joystick.joy1_x1, joystick.joy1_y1, 90);
    int y = rotateY(joystick.joy1_x1, joystick.joy1_y1, 90);
    int magnitude = sqrt(pow(joystick.joy1_x1,2)+pow(joystick.joy1_y1,2));
    int theta = radiansToDegrees(atan2(x,y));

    //nxtDisplayString(0, "%i", theta);
    //nxtDisplayString(1, "(%i, %i)", x,y);
    //nxtDisplayString(2, "(%i, %i)", joystick.joy1_x1,joystick.joy1_y1);
    //nxtDisplayString(3, "%i", magnitude);

    if ( magnitude <= 5 )
    {
      theta = 180;
      magnitude = 0;
    }

    int errorSum = 0;
    for ( int i = 0; i < 4; i++ )
      errorSum += abs(modules[i].turnPID.error);
    if ( (errorSum/4) > 40 )
      magnitude = 0;

    //debugPID(modules[2].turnPID);

    // nxtDisplayString(5, "%i", HTSPBreadADC(proto, 2, 10));
    //theta = 2.84444444*theta;
    if ( !joy1Btn(6) )
      magnitude = magnitude/3;

    massSet(theta*2.84444444, magnitude);
    //massSet(200);
    updateModule(0);
    updateModule(1);
    updateModule(2);
    updateModule(3);


    moduleRotationWatcher();
    //debugPID(modules[2].turnPID);
  }
}
